### ISSUE TITLE
error while running in local system

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [sxywu/expenses#7]
![image](https://cloud.githubusercontent.com/assets/9972828/13769077/90f9ba0a-eaa2-11e5-9a6d-335c9dc9b4ea.png)

**Comment by sxywu** [comment]
This is due to my lack of versioning for lodash and the rest of my dependencies in my package.json.  I will submit a change with the correct version numbers and let you know.

Thank you @Amara-Balakrishna1!

**Comment by sxywu** [comment]
Let me know if this fixes it for you @Amara-Balakrishna1 https://github.com/sxywu/expenses/commit/f564dbc93602535fbb9e86995ab07e1267662134
